#!/bin/sh
# Generates support/devtools/analyze's abort-only stub source (#97).
#
# movian-analyze links the real glw_view_{lexer,parser,preproc,support,
# attrib,eval}.o + misc/{pool,rstr,buf}.o objects, which were written to
# run inside the full application. shim.c hand-provides the ~11 symbols
# genuinely reachable while lexing/preprocessing/parsing a .view file
# (see the contract table at the top of shim.c); every OTHER undefined
# symbol left after that link is, by construction, only reachable from
# code paths movian-analyze never runs (evaluation, rendering, property
# subscriptions, widget construction, ...).
#
# Rather than hand-maintain that (large, and core-code-version-dependent)
# list, this script asks the linker what's still undefined and turns
# each one into `void SYM(void) { abort(); }`. If core GLW code ever
# grows a genuinely new PARSE-TIME dependency, the corresponding
# abort-stub fires during the corpus guard run (tests/tooling/glw/
# run_corpus.sh) instead of during real use -- that guard is what makes
# auto-generation safe here instead of just convenient.
#
# Usage: gen-abort-stubs.sh <output.c> <object-file>...
set -eu

OUT=$1
shift

TMP_LOG=$(mktemp)
trap 'rm -f "$TMP_LOG"' EXIT

# First link attempt without any abort stubs: whatever's still undefined
# at this point (after the real objects + shim.c) is abort-only.
cc "$@" -o /dev/null -lm -lpthread 2> "$TMP_LOG" || true

{
  echo "/* AUTO-GENERATED by $(basename "$0") -- DO NOT EDIT BY HAND."
  echo " * See the header comment in gen-abort-stubs.sh and the contract"
  echo " * table at the top of shim.c for what this is and why it is safe."
  echo " */"
  echo "#include <stdlib.h>"
  grep -o "undefined reference to \`[^']*'" "$TMP_LOG" \
    | sed "s/.*\`\(.*\)'/\1/" | sort -u \
    | while read -r sym; do
        [ -z "$sym" ] && continue
        echo "void $sym(void) { abort(); }"
      done
} > "$OUT"

n=$(grep -c '{ abort(); }' "$OUT" || true)
echo "gen-abort-stubs.sh: generated $n abort-only stub(s) into $OUT" >&2
